services:
  mcp-search:
    build: .
    container_name: mcp-search
    ports:
      - "8080:8080"
    volumes:
      - nltk_data:/root/nltk_data
    env_file: .env
    restart: unless-stopped

  searxng:
    profiles: ["all"]
    container_name: searxng
    image: searxng/searxng:latest
    ports:
      - "8081:8080"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml

volumes:
  nltk_data:
